name: cd-demo
stages:
- name: dev
  services:
  - name: linode/cd-test
- name: prod
  services:
  - name: cd-demo-workload-1/cd-test
    criteria:
      source: linode/cd-test
      secrets:
      - tag
edges:
- from: dev
  to: prod
  gates:
  - name: Approve
    type: approval