{{- if and .Values.grafana.enabled (eq .Values.grafana.database.type "postgres") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cd-demo.fullname" . }}-grafana-db
  labels:
    {{- include "cd-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  password: {{ .Values.grafana.database.password | b64enc | quote }}
{{- end }}
