{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cd-demo.fullname" . }}-grafana
  labels:
    {{- include "cd-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: grafana
      protocol: TCP
      name: grafana
  selector:
    {{- include "cd-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
{{- end }}
